# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('diametro_min', models.DecimalField(decimal_places=2, max_digits=20)),
                ('diametro_max', models.DecimalField(decimal_places=2, max_digits=20)),
                ('url', models.URLField()),
                ('is_potentially_hazardous_asteroid', models.BooleanField()),
            ],
        ),
    ]
