# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asteroide',
            old_name='is_potentially_hazardous_asteroid',
            new_name='is_dangerous',
        ),
        migrations.AlterField(
            model_name='asteroide',
            name='diametro_max',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asteroide',
            name='diametro_min',
            field=models.CharField(max_length=200),
        ),
    ]
